---
# /etc/mosdns/config.yaml

## -- Log Config -- ##
log:
  level: debug # ["debug", "info", "warn", and "error"], default is set to "info"
  production: true
  # file: "/var/log/mosdns.log"

## -- API Config -- ##
api:
  http: "0.0.0.0:9999"

plugins: 
  ## --- Cache --- ##
  - tag: cache
    type: cache
    args:
      size: 10240
      lazy_cache_ttl: 86400 # ttl set to 86400 (1 day) or to 0 (off)
      dump_file: ./cache.dump # persist cache to a local file, loaded when service starts
      dump_interval: 600 # autosave interval (s)

  ## --- Domain Set --- ##
  - tag: "local_domain_set"
    type: domain_set
    args:
      exps:
        - "homelab.sh"

  - tag: "ads_domain_set"
    type: domain_set
    args:
      files:
        - "./domains/reject.txt"
        - "./domains/category-ads-all.txt"

  - tag: "remote_domain_set"
    type: domain_set
    args:
      files:
        - "./custom/remote.txt"
        - "./domains/gfw.txt"
        - "./domains/google-scholar.txt"
        - "./domains/linkedin.txt"
        - "./domains/netflix.txt"
        - "./domains/openai.txt"
        - "./domains/icloud.txt"
        - "./domains/apple.txt"
        - "./domains/apple-cn.txt"
        - "./domains/twitter.txt"
        - "./domains/telegram.txt"
        - "./domains/google.txt"
        - "./domains/twitter.txt"
        - "./domains/yahoo.txt"
        - "./domains/microsoft.txt"
        - "./domains/cloudflare.txt"
        - "./domains/cloudflare-cn.txt"
        - "./domains/speedtest.txt"
        - "./domains/github.txt"
        - "./domains/category-container.txt"
        - "./domains/category-dev.txt"
        - "./domains/geolocation-!cn.txt"
        - "./domains/category-scholar-!cn.txt"

  - tag: "direct_domain_set"
    type: domain_set
    args:
      files:
        - "./custom/direct.txt"
        - "./domains/alibaba.txt"
        - "./domains/bilibili.txt"
        - "./domains/bilibili2.txt"
        - "./domains/tencent.txt"
        - "./domains/zhihu.txt"
        - "./domains/category-scholar-cn.txt"
        - "./domains/category-media-cn.txt"
        - "./domains/category-social-media-cn.txt"
        - "./domains/category-dev-cn.txt"
        - "./domains/category-bank-cn.txt"
        - "./domains/direct.txt"
        - "./domains/cn.txt"
        - "./domains/geolocation-cn.txt"

  ## --- IP Set --- ##
  - tag: "direct_ip"
    type: ip_set
    args:
      files:
        - "./ips/cn.txt"

  ## --- Upstream Servers --- ##
  - tag: "local_forward"
    type: forward
    args:
      upstreams: 
       ## --- Local DNS Servers --- ##
        - tag: pihole
          addr: "10.178.0.6"

  - tag: "remote_forward"
    type: forward
    args:
      upstreams: 
        ##  --- Remote DNS Servers --- ##
        - tag: opendns_dot
          addr: "tls://dns.opendns.com"
          dial_addr: "208.67.222.222"
          enable_pipeline: true
          idle_timeout: 86400
          insecure_skip_verify: true

  - tag: "domestic_forward"
    type: forward
    args:
      upstreams: 
       ## --- Domestic DNS Servers --- ##
        - tag: ali_dot
          addr: "tls://dns.alidns.com"
          dial_addr: "223.5.5.5"
          enable_pipeline: true
          idle_timeout: 86400
          insecure_skip_verify: true

  ## -- TTL Sequence -- ##
  - tag: "ttl_sequence"
    type: sequence
    args:
      - exec: ttl 600-3600
      - exec: accept

  - tag: "local_sequence"
    type: sequence
    args:
      - exec: query_summary local_forward
      - exec: $local_forward

  - tag: "domestic_sequence"
    type: sequence
    args:
      - exec: query_summary domestic_forward
      - exec: $domestic_forward
      - exec: goto ttl_sequence

  - tag: "remote_sequence"
    type: sequence
    args:
      - exec: query_summary remote_forward
      - exec: $remote_forward
      - matches: "resp_ip $direct_ip"
        exec: goto domestic_sequence
      - exec: goto ttl_sequence

  ## --- Fallback IP Sequence --- ##
  # if response has direct IP, drop it
  - tag: "direct_ip_sequence"
    type: sequence
    args:
      - exec: goto remote_sequence
      - matches: "resp_ip $direct_ip"
        exec: drop_resp
  
  ## --- Fallback --- ##
  - tag: "fallback"
    type: fallback
    args:
      primary: direct_ip_sequence
      secondary: remote_sequence
      threshold: 500  # no response timeout, default value is 500ms
      always_standby: true

  ## --- Main Sequence --- ##
  - tag: "main_sequence"
    type: sequence
    args:
      - exec: prefer_ipv4

      - matches: "qname $local_domain_set"
        exec: goto local_sequence

      - exec: $cache # enable cache
      - matches: has_resp
        exec: accept # end if reponse found in cache

      - matches: qtype 12
        exec: reject 3
      - matches: qtype 65
        exec: reject 3

      - matches: "qname $ads_domain_set" # block ads
        exec: reject 0

      - matches: "qname $remote_domain_set"
        exec: goto remote_sequence

      - matches: "qname $direct_domain_set"
        exec: goto domestic_sequence

      - exec: $fallback # not recommended to use unless you know what you are doing

  - tag: udp_server
    type: udp_server
    args:
      entry: main_sequence
      listen: :53
